name: Deploy Portfolio to GitHub Pages

# Trigger - specifying to only run this script when pushed on main branch.
on:
  push:
    branches:
      - main

# Job Setup - where to run this script, temporary computer (virtual machine) - ubuntu here
jobs:
  deploy:
    name: Deploy Portfolio to GitHub Pages
    runs-on: ubuntu-latest

    # Steps - what exactly to do
    steps:
      - uses: actions/checkout@v4   # Github is telling ubuntu to copy Portfolio repository 
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4  # Ubuntu installing Node 20 for Docusaurus 
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies   # Ubuntu installing 'package.json' libraries 
        run: npm ci

      - name: Build website     # to build website, converts markdowns into pure HTML/CSS
        run: npm run build

      # Publishing to web 
      - name: Deploy Portfolio to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
